debug

diff --git a/.github/workflows/manual_build.yml b/.github/workflows/manual_build.yml
--- a/.github/workflows/manual_build.yml
+++ b/.github/workflows/manual_build.yml
@@ -220,6 +220,9 @@ jobs:
       matrix:
         target: [linuxarm64]
         variant: [gpl 6.1-rk]
+    env:
+      ACTIONS_RUNNER_DEBUG: true
+      ACTIONS_STEP_DEBUG: true  # Enable step-level debug logging
     steps:
       - name: Free Disk-Space
         run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h
@@ -231,10 +234,18 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GHCR_PAT }}
+      - name: Check pkg-config for rockchip_mpp
+        run: |
+          pkg-config --modversion rockchip_mpp || echo "pkg-config for rockchip_mpp failed"
       - name: Build ffmpeg
         run: |
           T="$(echo -n ${{ github.token }} | sha256sum | head -c 64)" && echo -e "::add-mask::${T}\n::stop-commands::${T}"
           ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
+      - name: Upload build logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: ffmpeg-build-logs
+          path: build.log
       - name: Replace spaces in string
         id: strs
         run: |
